### ISSUE TITLE
Index Out of Range

### ISSUE THREAD

**Issue by btotharye** [MycroftAI/skill-installer#8]
Getting below error when trying to use skill, appears there might be a code issue here.

```
2017-09-21 14:41:22,148 - mycroft.skills.core - ERROR - An error occurred while processing a request in SkillInstallerSkill
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.8.22-py2.7.egg/mycroft/skills/core.py", line 356, in wrapper
    handler(message)
  File "/opt/mycroft/skills/skill-installer/__init__.py", line 55, in install
    elif text.splitlines()[2] == "Skill installed!":
IndexError: list index out of range
```

**Comment by forslund** [comment]
This is likely fixed in PR #7 I'm just finishing testing it out...
